antenaaanpcbccccccc% Script generated by antennaDesigner 
% Matlab antenna designer example 
% Based on video available in Robert Feranec YT channel
% Joao Colombari - March 2023, Brazil.

%%
close all;
clear all;

%% Antenna Properties   
% More commands are shown with cmd. methods(antennaObject)

fc = 2400e6;                                     % Define plot frequency  
freqRange = (216:2.4:264) * 1e7;                % Define frequency range

antennaObject = design(invertedFcoplanar, fc);  % Define antenna 

antennaObject.RadiatorArmWidth = 0.0013879;     % Define sizes 
antennaObject.FeederArmWidth = 0.0013879;

figure;
show(antennaObject)                             % show for invertedFcoplanar

%% Antenna Analysis
figure;
impedance(antennaObject, freqRange)             % impedance for invertedFcoplanar

figure;
s = sparameters(antennaObject, freqRange);      
rfplot(s)                                       % s11 for invertedFcoplanar

figure;
current(antennaObject, fc)           % current for invertedFcoplanar

figure;
pattern(antennaObject, fc)           % pattern for invertedFcoplanar

figure;
patternAzimuth(antennaObject, fc)    % azimuth for invertedFcoplanar

%% Putting it on a PCB

pcbAnt = pcbStack(antennaObject);
pcbAnt.BoardThickness = 1e-3;

d1 = dielectric('FR4');
d1.EpsilonR = 4.5;
d1.Thickness = 1e-3;

pcbAnt.Layers{2} = d1; 
pcbAnt.BoardShape = antenna.Rectangle('Length',antennaObject.GroundPlaneLength, ... 
    'Width',antennaObject.GroundPlaneWidth+2*antennaObject.Height, ...
    'Center',[0 antennaObject.Height]);
show(pcbAnt)

%% New analysis

figure;
impedance(antennaObject, freqRange)      
figure;
impedance(pcbAnt, freqRange)             % Shows both in order to campare  

